title: "2025 IMS New Researchers Conference"
author: "NRC 2025 Organizers"
description: "2025 IMS New Researchers Conference"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  - {file: "application.md", title: Application}
  - {file: "venue.md", title: Venue}
  - {file: "speakerstemp.md", title: Speakers}
  - {file: "organizers.md", title: Organizers}

# external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  # - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  # - {title: NRC, icon: internet-explorer, url: "https://www.imsnrg.com/home"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
